# Docker Compose for IremboCare+ Production Deployment
# Use this for Part 2A deployment with load balancing
version: '3.8'

services:
  # Application instance 1 (for Web01)
  irembocare-web01:
    image: ${DOCKER_USERNAME}/irembocare:${VERSION:-latest}
    container_name: irembocare-web01
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - RAPIDAPI_KEY=${RAPIDAPI_KEY}
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - NEWS_API_KEY=${NEWS_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  # Application instance 2 (for Web02)
  irembocare-web02:
    image: ${DOCKER_USERNAME}/irembocare:${VERSION:-latest}
    container_name: irembocare-web02
    ports:
      - "8081:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - RAPIDAPI_KEY=${RAPIDAPI_KEY}
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - NEWS_API_KEY=${NEWS_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

networks:
  default:
    name: irembocare-prod-network
    driver: bridge

volumes:
  logs:
    driver: local