# Docker Compose for IremboCare+ Development
version: '3.8'

services:
  irembocare:
    build:
      context: .
      target: development
    container_name: irembocare-dev
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
      - RAPIDAPI_KEY=${RAPIDAPI_KEY}
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - NEWS_API_KEY=${NEWS_API_KEY}
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a simple load balancer for testing
  nginx:
    image: nginx:alpine
    container_name: irembocare-lb
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - irembocare
    restart: unless-stopped

networks:
  default:
    name: irembocare-network