@echo off
echo Starting IremboCare+ Application...
echo.
echo Checking Node.js...
node --version
echo.
echo Installing dependencies...
npm install
echo.
echo Starting the application...
node src/app.js
pause 